fx

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -54,6 +54,25 @@ jobs:
           fi
         done
 
+    - name: Test Azure endpoint
+      run: |
+        combinations=(
+          "region=westus2&ipv4=true:200"
+          "region=eastus&system_service=azurestorage&ipv4=true&ipv6=true:200"
+          "system_service=azurestorage:404"
+          "ipv4=true:200"
+          "ipv6=true:200"
+          ":404"
+        )
+        for combo in "${combinations[@]}"; do
+          IFS=":" read params expected <<< "$combo"
+          status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8000/v1/azure?$params")
+          if [ $status -ne $expected ]; then
+            echo "Azure test failed for params: $params. Expected $expected, got $status"
+            exit 1
+          fi
+        done
+
     - name: Test GCP endpoint
       run: |
         combinations=(
@@ -69,25 +88,6 @@ jobs:
           status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8000/v1/gcp?$params")
           if [ $status -ne $expected ]; then
             echo "GCP test failed for params: $params. Expected $expected, got $status"
-            exit 1
-          fi
-        done
-
-    - name: Test Azure endpoint
-      run: |
-        combinations=(
-          "region=westus2&ipv4=true:200"
-          "region=eastus&system_service=azurestorage&ipv4=true&ipv6=true:200"
-          "system_service=azurestorage:200"
-          "ipv4=true:200"
-          "ipv6=true:200"
-          ":404"
-        )
-        for combo in "${combinations[@]}"; do
-          IFS=":" read params expected <<< "$combo"
-          status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8000/v1/azure?$params")
-          if [ $status -ne $expected ]; then
-            echo "Azure test failed for params: $params. Expected $expected, got $status"
             exit 1
           fi
         done
